### ISSUE TITLE
Ledge Jumping not working

### ISSUE THREAD

**Issue by GeorgeDOC2003** [knela96/Dynamic-Parkour-System#10]
I've been using this code for a college project. I've been trying to get ledge-ledge jumping working but the character will just be stuck in place when I try. Previously there were error messages saying I needed to assign the hand and feet values in the Climbcontroller script. I couldn't access the hand and feet objects from the inspector so I set it to the Player prefab, because the models are in there. I also set the hand and feet values inside the player prefab itself to the hand and feet objects. I stopped getting the error but it still wouldn't work.

**Comment by knela96** [comment]
Watch the following video and check everything is configured like that, you'll see that there is a checkbox that I activate on the prefab to detect the hands and feet https://www.youtube.com/watch?v=h4n7_3nTsLE.

Let me know if it works

**Comment by GeorgeDOC2003** [comment]
Hi! Thanks for the fast reply. 

I double checked and as far as I could tell everything in the video had been copied and done perfectly. I'm not getting error messages anymore but it still isn't working for me. We're using the included player prefab as we haven't finished our character model yet. We haven't fiddled with any of the scripts or prefabs to my knowledge.

I have included the current build of our game. I apologize for the messy organization, the whole team is very new to this.

Hope to hear from you again!

https://drive.google.com/file/d/1mBlFtasgex9I3S8h3jX2mKYFccN6lLDN/view?usp=sharing

(Sorry about the drive link, I was having issues uploading the .zip directly to github)

**Comment by knela96** [comment]
I will hide the comment so I can be the only one to see for you're privacy @GeorgeDOC2003

**Comment by knela96** [comment]
I'll have a look later today ;)

**Comment by knela96** [comment]
Hey sorry for the delay I was a little bit busy, You missed some important parts on the documentation about how to prepare the Ledges. You need a Ledge Manager first of all as a parent and set the values Min and Max distance to find possible jump points. After that go to reset and Update Connections, To see if they are connected activate the refresh checkbox
![image](https://user-images.githubusercontent.com/27001185/169139846-da48acb1-3578-4805-898b-3ffdf0fbf8d3.png)
![image](https://user-images.githubusercontent.com/27001185/169140785-a057e1d2-d8ad-459a-8737-7c1d8e179472.png)

- Also the player has to be in the Player Layer not the Ledges as you had. 
- Really important to deactivate Player and Ledge physics between these layers on Project Settings
![image](https://user-images.githubusercontent.com/27001185/169140604-ddf67c5b-fb79-4023-8ad2-e29d656ba6bb.png)
- Another thing was the climbing offsets of the hands that where not correctly set 
![image](https://user-images.githubusercontent.com/27001185/169140418-80dfef74-1315-4350-a10e-774c0b455a51.png)
![image](https://user-images.githubusercontent.com/27001185/169140511-100450fb-24ad-4770-84f2-f7c25bcd8659.png)
