### ISSUE TITLE
Plugin license

### ISSUE THREAD

**Issue by gleblebedev** [knela96/Dynamic-Parkour-System#13]
I would like to port the plugin into a different game engine ( https://github.com/rbfx/rbfx ) but the plugin license is not compatible with MIT. Is there a particular reason in picking GPL-3.0 license? Does it mean that games using the plugin should be open-sourced under GPL license too?

**Comment by knela96** [comment]
You can use the plugin under any other license that your game is, but if you make any modification on the plugin it has to follow the GPL 3.0

**Comment by gleblebedev** [comment]
It won't be a modification but complete rewrite in c++. Just to be clear - I can't do that, am I right?

Ok, I have to write it from scratch then :-(
