### ISSUE TITLE
InputSystem Error

### ISSUE THREAD

**Issue by shine5325** [knela96/Dynamic-Parkour-System#14]
![Test Mobile Game - Testing - Windows, Mac, Linux - Unity 2022 1 9f1 _DX11_ 01-09-2022 15_15_57](https://user-images.githubusercontent.com/112622300/187886245-0de30cb0-b993-46a5-80b4-48dbf2bebdaa.png)
its showing me this error how to Solve this?? I Already Changed My Old Input System To New But It Still Showing me this issue

**Comment by CACcodes** [comment]
Make sure you open the PDF that came with the package, those instructions will solve everything.
