### ISSUE TITLE
The Scriptable Action script is causing multiple conflicts with Unity Actions delegate

### ISSUE THREAD

**Issue by SamRockX** [knela96/Dynamic-Parkour-System#6]
The Scriptable Action script is causing multiple conflicts with Unity Actions delegate

error: Assets\Krearthur\GOPainter\Scripts\GOPainter.cs(196,29): error CS0066: 'GOPainter.OnGOPainterDeactivated': event must be of a delegate type

![image](https://user-images.githubusercontent.com/7374386/132255990-42cff3ca-6f92-42d3-b9fe-1ccbc3375b8f.png)

![image](https://user-images.githubusercontent.com/7374386/132256029-abca650e-420e-4605-9ffa-e9f404267637.png)

![image](https://user-images.githubusercontent.com/7374386/132256037-5f2c183e-c227-4444-bcb6-b1b402e83f22.png)

**Comment by SamRockX** [comment]
Renaming "Action" to something like "ParkourAction" seems to fix the issue

**Comment by SteffanoDeMoura** [comment]
it would be better to surround the whole system with its own namespace.

**Comment by knela96** [comment]
Working on the Fix Thnx

**Comment by knela96** [comment]
@SamRockX Could you download the [v1.0.1](https://github.com/knela96/Dynamic-Parkour-System/releases/tag/v1.0.1) and confirm if the errors disappear? 
I forgot to include the namespace "Climbing" as @SteffanoDeMoura suggested.

**Comment by SamRockX** [comment]
@knela96 Thank you for the quick fix! The new version removed all errors :)
