### ISSUE TITLE
Problem in the PlayerControls.cs

### ISSUE THREAD

**Issue by Kinox7** [knela96/Dynamic-Parkour-System#9]
When I import the package into Unity, I get multiple errors inside the "PlayerControls.cs" script:

![Parkour_System_Problem](https://user-images.githubusercontent.com/51831454/147361719-1f6a9379-85fe-4bfc-972e-f4aec9404fb0.png)

**Comment by knela96** [comment]
Hi! For the plugin to work you need the Cinemachine and New Input System from Unity. I recommend you to follow the documentated steps on how to setup your project in the pdf included within the package. Let me know if that fixes your problem to have a better look.

**Comment by knela96** [comment]
@Kinox7 Is it solved?
